name: my-first-commit

on:
    push:
        branches:
            - flask

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - name: Print Hello Message
          run: echo "Hello, World from test"

    deploy:
        runs-on: ubuntu-latest
        needs: [test]
        steps:
        - name: Print Hello Message
          run: echo "Hello, World from deploy"