name: my-first-action

on:
  push:
    branches:
      - flask

jobs:
  first-build:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello Message
      run: echo "Hello, World form first-build"
        
  second-build:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello Message
      run: echo "Hello, World from second-build"
        
