name: my-first-commit
env:
    APPLICATION_NAME: "MyFirstFlask"
    DEPLOY_PACKAGE_NAME: "flask-deploy-ver-${{ github.sha }}"

on:
    push:
        branches:
            - flask

jobs:
    test:
        runs-on: ubuntu-latest222
        steps:
        - name: Print Hello Message
          run: echo "Hello, World from test"

        - name: Execute few commands
          run: |
            echo "Hello Mes1"
            echo "Hello Mes2"
            echo "App name: ${{ env.APPLICATION_NAME }}"

        - name: Check empty folder
          run: ls -la

        - name: Clone Git
          uses: actions/checkout@v1

        - name: List not empty folder
          run: ls -la

    deploy:
        runs-on: ubuntu-latest
        needs: [test]
        env:
            VAR_1: "This is varible 1"
            VAR_2: "This is varible 2"
            VAR_3: "This is varible 3"

        steps:
        - name: Print Hello Message
          run: echo "Hello, World from deploy"

        - name: Print env vars
          run: |
            echo "Var 1 = ${{ env.VAR_1 }}"
            echo "Var 2 = ${{ env.VAR_2 }}"
            echo "Var 3 = ${{ env.VAR_3 }}"
            echo "Local var 1 = $LOCAL_VAR_1"
            echo "Local var 2 = $LOCAL_VAR_2"
          env:
            LOCAL_VAR_1: "This is local var 1"
            LOCAL_VAR_2: "This is local var 2"

        - name: Print dep packege name
          run: |
            echo "Hello Messgae 1"
            echo "Hello Message 2"
            echo "Hello Message 3"
            echo "Dep ver ${{ env.DEPLOY_PACKAGE_NAME }}"
        
        - name: Test some packeges if they are here 1
          run: aws --version

        - name: Test some packages if they are here 2
          run: zip --version